### ISSUE TITLE
Epic: Backend in JS

### ISSUE THREAD

**Issue by phated** [noir-lang/acvm-backend-barretenberg#161]
### Problem

We want to consume the Backend in JS.

### Proposed solution

This requires multiple things:
```[tasklist]
- [ ] 1.  Async fetching of the CRS (resolved by #160)
- [ ] 2. Removing filesystem access from CRS code (resolved by #160)
- [ ] 3. Separate implementation for JS to use browser fetch (resolved by #185)
- [ ] 4. WASI randomness function doesn't seem to have access to memory in JS
- [x] 5. Upgrade to Wasmer 3.3 (resolved by #200)
- [ ] https://github.com/noir-lang/acvm-backend-barretenberg/issues/201
```

### Submission Checklist

- [X] Once I hit submit, I will assign this issue to the Project Board with the appropriate tags.

**Comment by Globallager** [comment]
Does this supersedes https://github.com/noir-lang/acvm-backend-barretenberg/issues/98?

**Comment by Savio-Sou** [comment]
Closing as this is no longer relevant.
